default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: rootpassword
  host: db

development:
  <<: *default
  database: techpit_success_development

test:
  <<: *default
  database: techpit_success_test

production:
  <<: *default
  database: techpit_success_production
